---
## Tor section
- name: restart tor
  service:
    name: tor
    state: restarted

- name: reload iptables rules for xenial
  shell: iptables-restore < /etc/network/iptables/rules_v4
  when:
    - ansible_distribution_release == 'xenial'

- name: reload iptables rules for focal
  shell: iptables-restore < /etc/iptables/rules.v4
  when:
    - ansible_distribution_release == 'focal'

## App/securedrop section
- name: restart apache2
  service:
    name: apache2
    state: restarted

## Here, we list apparmor before haveged to ensure the correct AppArmor
## profile is loaded prior to restarting haveged
- name: restart apparmor
  service:
    name: apparmor
    state: restarted

- name: restart haveged
  service:
    name: haveged
    state: restarted
