---
- name: Install SecureDrop apt repo GPG signing key.
  apt_key:
    state: present
    data: "{{ lookup('file', item) }}"
    keyring: /etc/apt/trusted.gpg.d/securedrop-keyring.gpg
  with_items: "{{ apt_repo_pubkey_files }}"
  tags:
    - apt
    - fpf_repo

- name: Setup FPF apt repo.
  apt_repository:
    repo: deb [arch=amd64] {{ apt_repo_url }} {{ apt_repo_target_distro }} main
    state: present
    update_cache: no
  tags:
    - apt
    - fpf_repo

- name: Update apt cache.
  shell: apt-get update -q

- name: Install the securedrop-keyring package for managing the apt gpg key.
  apt:
    pkg: securedrop-keyring
    state: present
  # Skip installing the keyring package from the apt repo under staging.
  when: not install_local_packages
