---
- name: Install resolvconf
  apt:
    pkg: resolvconf
    state: latest
  tags:
    - apt
    - dns

- name: Configure DNS server IP.
  template:
    src: dns_base
    dest: /etc/resolvconf/resolv.conf.d/base
  tags:
    - dns
    - hardening
