---
- name: Configure DNS server IP.
  template:
    src: dns_base
    dest: "{{ resolvconf_target_filepath }}"
  tags:
    - dns
    - hardening

- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
  tags:
    - dns
    - hardening
